spring:
  application:
    name: backend
  datasource:
    #url: jdbc:mysql://localhost:3306/vfin
    #username: root
    #password: root
    #driver-class-name: com.mysql.cj.jdbc.Driver
#    url:jdbc:h2:mem:testdb
#    driverClassName:org.h2.Driver
#    username:sa
#    password:password
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: vfin_usr
    password: root
  flyway:
    #clean-disabled: true         # Prevents Flyway from wiping the whole DB - should we used in prod with true
    baseline-on-migrate: true     # Tells Flyway to assume the current DB is already at the base version
    baselineVersion: 0
    #create-schemas: true         #  V - versioned migration, U - undo,  R - repeatable, b - baseline



