CREATE TABLE APP_USER (
    ID           RAW(16) PRIMARY KEY,
    APP_USER_ID  VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    FIRST_NAME   VARCHAR2(255 CHAR) NOT NULL,
    LAST_NAME    VARCHAR2(255 CHAR) NOT NULL,
    EMAIL        VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    USER_STATUS  VARCHAR2(64 CHAR)  NOT NULL
);

CREATE TABLE APP_USER_ROLE (
    USER_ID RAW(16) NOT NULL,
    ROLE    VARCHAR2(64 CHAR) NOT NULL,
    PRIMARY KEY (USER_ID, ROLE),
    FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID)
);



CREATE TABLE USER_GROUP (
    ID     RAW(16) PRIMARY KEY,
    TITLE  VARCHAR2(255 CHAR) NOT NULL
);


CREATE TABLE TEAM (
    ID     RAW(16) PRIMARY KEY,
    TITLE  VARCHAR2(255 CHAR) NOT NULL
);


CREATE TABLE TEAM_MEMBER (
    TEAM_ID     RAW(16) NOT NULL,
    USER_ID     RAW(16) NOT NULL,
    ACCESS_TYPE VARCHAR2(64 CHAR) NOT NULL,
    PRIMARY KEY (TEAM_ID, USER_ID),
    CONSTRAINT FK_TEAM_MEMBER_TEAM FOREIGN KEY (TEAM_ID) REFERENCES TEAM(ID),
    CONSTRAINT FK_TEAM_MEMBER_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID)
);

CREATE TABLE USER_GROUP_MEMBERS (
    USER_GROUP_ID RAW(16) NOT NULL,
    TEAM_ID       RAW(16) NOT NULL,
    PRIMARY KEY (USER_GROUP_ID, TEAM_ID),
    CONSTRAINT FK_USER_GROUP_MEMBERS_GROUP FOREIGN KEY (USER_GROUP_ID) REFERENCES USER_GROUP(ID),
    CONSTRAINT FK_USER_GROUP_MEMBERS_TEAM FOREIGN KEY (TEAM_ID) REFERENCES TEAM(ID)
);



CREATE TABLE PROJECT (
    ID              RAW(16) PRIMARY KEY,
    PROJECT_NUMBER  VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    PROJECT_TITLE   VARCHAR2(255 CHAR) NOT NULL,
    PROJECT_STATUS  VARCHAR2(64 CHAR)  NOT NULL,
    USER_GROUP_ID   RAW(16)            NOT NULL,    
    CONSTRAINT FK_PROJECT_USERGROUP FOREIGN KEY (USER_GROUP_ID) REFERENCES USER_GROUP(ID)
);


CREATE TABLE PLANT (
    ID    RAW(16) PRIMARY KEY,
    CODE  VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    NAME  VARCHAR2(255 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY RAW(16) NOT NULL,
    MODIFIED_AT TIMESTAMP WITH TIME ZONE,
    MODIFIED_BY RAW(16)
);


CREATE TABLE AUDIT_LOG (
    ID           RAW(16) PRIMARY KEY,
    USER_ID      RAW(16) NOT NULL,
    REQUEST_TYPE VARCHAR2(255 CHAR) NOT NULL,
    REQUEST_BODY CLOB,
    TIMESTAMP    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT FK_AUDIT_LOG_USER
        FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID)
);
