
CREATE TABLE APP_USER (
    ID           RAW(16) PRIMARY KEY,
    APP_USER_ID  VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    FIRST_NAME   VARCHAR2(255 CHAR) NOT NULL,
    LAST_NAME    VARCHAR2(255 CHAR) NOT NULL,
    EMAIL        VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    USER_STATUS  VARCHAR2(64 CHAR)  NOT NULL
);

CREATE TABLE PLANT (
    ID    RAW(16) PRIMARY KEY,
    CODE  VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    NAME  VARCHAR2(255 CHAR) NOT NULL
);

CREATE TABLE PROJECT (
    ID             RAW(16) PRIMARY KEY,
    PROJECT_NUMBER VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    PROJECT_TITLE  VARCHAR2(255 CHAR) NOT NULL,
    PROJECT_STATUS  VARCHAR2(64 CHAR)  NOT NULL
);

CREATE TABLE AUDIT_LOG (
    ID           RAW(16) PRIMARY KEY,
    USER_ID      RAW(16) NOT NULL,
    REQUEST_TYPE VARCHAR2(255 CHAR) NOT NULL,
    REQUEST_BODY CLOB,
    TIMESTAMP    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT FK_AUDIT_LOG_USER
        FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID)
);
