CREATE TABLE APP_USER (
    ID           RAW(16) PRIMARY KEY,
    APP_USER_ID  VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    FIRST_NAME   VARCHAR2(255 CHAR) NOT NULL,
    LAST_NAME    VARCHAR2(255 CHAR) NOT NULL,
    EMAIL        VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    USER_STATUS  VARCHAR2(64 CHAR)  NOT NULL
);

CREATE TABLE APP_USER_ROLE (
    USER_ID RAW(16) NOT NULL,
    ROLE    VARCHAR2(64 CHAR) NOT NULL,
    PRIMARY KEY (USER_ID, ROLE),
    FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID)
);


CREATE TABLE USER_GROUP (
    ID     RAW(16) PRIMARY KEY,
    TITLE  VARCHAR2(255 CHAR) NOT NULL
);


CREATE TABLE TEAM (
    ID     RAW(16) PRIMARY KEY,
    TITLE  VARCHAR2(255 CHAR) NOT NULL
);


CREATE TABLE TEAM_MEMBER (
    TEAM_ID     RAW(16) NOT NULL,
    USER_ID     RAW(16) NOT NULL,
    ACCESS_TYPE VARCHAR2(64 CHAR) NOT NULL,
    PRIMARY KEY (TEAM_ID, USER_ID),
    CONSTRAINT FK_TEAM_MEMBER_TEAM FOREIGN KEY (TEAM_ID) REFERENCES TEAM(ID),
    CONSTRAINT FK_TEAM_MEMBER_USER FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID)
);

CREATE TABLE USER_GROUP_MEMBERS (
    USER_GROUP_ID RAW(16) NOT NULL,
    TEAM_ID       RAW(16) NOT NULL,
    PRIMARY KEY (USER_GROUP_ID, TEAM_ID),
    CONSTRAINT FK_USER_GROUP_MEMBERS_GROUP FOREIGN KEY (USER_GROUP_ID) REFERENCES USER_GROUP(ID),
    CONSTRAINT FK_USER_GROUP_MEMBERS_TEAM FOREIGN KEY (TEAM_ID) REFERENCES TEAM(ID)
);



CREATE TABLE PROJECT (
    ID              RAW(16) PRIMARY KEY,
    PROJECT_NUMBER  VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    PROJECT_TITLE   VARCHAR2(255 CHAR) NOT NULL,
    PROJECT_STATUS  VARCHAR2(64 CHAR)  NOT NULL,
    USER_GROUP_ID   RAW(16)            NOT NULL,    
    CONSTRAINT FK_PROJECT_USERGROUP FOREIGN KEY (USER_GROUP_ID) REFERENCES USER_GROUP(ID)
);


CREATE TABLE PLANT (
    ID    RAW(16) PRIMARY KEY,
    CODE  VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    NAME  VARCHAR2(255 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY RAW(16) NOT NULL,
    MODIFIED_AT TIMESTAMP WITH TIME ZONE,
    MODIFIED_BY RAW(16)
);


CREATE TABLE AUDIT_LOG (
    ID           RAW(16) PRIMARY KEY,
    USER_ID      RAW(16) NOT NULL,
    REQUEST_TYPE VARCHAR2(255 CHAR) NOT NULL,
    REQUEST_BODY CLOB,
    TIMESTAMP    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT FK_AUDIT_LOG_USER
        FOREIGN KEY (USER_ID) REFERENCES APP_USER(ID)
);


CREATE TABLE SYSTEM_SETTING (
  SETTING_KEY VARCHAR2(128) PRIMARY KEY,
  SETTING_VALUE CLOB NOT NULL -- STORES JSON AS STRING IF NEEDED
);

-- CURRENCY TABLE
-- DEFINES ALL CURRENCIES USED IN THE SYSTEM WITH THEIR VALIDITY RANGE.
CREATE TABLE CURRENCY (
    CODE VARCHAR2(3) PRIMARY KEY,
    NAME VARCHAR2(64) NOT NULL,
    VALID_FROM NUMBER(6) NOT NULL,  -- stored as YYYYMM
    VALID_TO NUMBER(6)              -- nullable
);

-- EXCHANGE RATE VERSION TABLE
-- GROUPS A CONSISTENT SET OF EXCHANGE RATES WITH METADATA
CREATE TABLE EXCHANGE_RATE_VERSION (
    ID RAW(16) PRIMARY KEY,
    VERSION_NAME VARCHAR2(32) NOT NULL UNIQUE,  -- E.G. 'BUDGET_2025_V1'
    DESCRIPTION VARCHAR2(1000) NOT NULL,        -- E.G. DESCRIPTION OF THIS VERSION
    STATUS VARCHAR2(255) NOT NULL,              -- DRAFT, RELEASED, ETC.
    CONSOLIDATION_CURRENCY_CODE VARCHAR2(3) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CREATED_BY RAW(16) NOT NULL,
    MODIFIED_AT TIMESTAMP WITH TIME ZONE,
    MODIFIED_BY RAW(16),
    RELEASED_AT TIMESTAMP,                     -- ADDED TO SUPPORT RELEASED STATUS CHECK

    -- CONSTRAINTS
    CONSTRAINT FK_CONSOLIDATION_CURRENCY_CODE FOREIGN KEY (CONSOLIDATION_CURRENCY_CODE) REFERENCES CURRENCY(CODE)
);

-- EXCHANGE RATE TABLE
-- STORES EXPLICIT MONTHLY CONVERSION RATES BETWEEN CURRENCY PAIRS
-- ALL CURRENCIES MUST BE VALID (FROM THE CURRENCY TABLE) AT THE RELEASE DATE OF THEIR VERSION
CREATE TABLE EXCHANGE_RATE (
    VERSION_ID       RAW(16)     NOT NULL,
    CURRENCY_FROM    VARCHAR2(3)  NOT NULL,
    CURRENCY_TO      VARCHAR2(3)  NOT NULL,
    YEAR_MONTH       NUMBER(6)     NOT NULL,  -- FORMAT: YYYYMM
    RATE_VALUE       NUMBER(20, 10) NOT NULL,

    CONSTRAINT PK_EXCHANGE_RATE PRIMARY KEY (VERSION_ID, CURRENCY_FROM, CURRENCY_TO, YEAR_MONTH),
    CONSTRAINT FK_VERSION_ID FOREIGN KEY (VERSION_ID) REFERENCES EXCHANGE_RATE_VERSION(ID),
    CONSTRAINT FK_CURRENCY_FROM FOREIGN KEY (CURRENCY_FROM) REFERENCES CURRENCY(CODE),
    CONSTRAINT FK_CURRENCY_TO FOREIGN KEY (CURRENCY_TO) REFERENCES CURRENCY(CODE),
    CONSTRAINT CHK_NO_SELF_CONVERSION CHECK (CURRENCY_FROM <> CURRENCY_TO)
);

